const ALLOWED_OPERATIONS = ["GET", "PUT", "PATCH", "DELETE"];

const AVAILABLE_SUBJECTS = [
  "LANG_JAVA",
  "LANG_CPP",
  "LANG_CS",
  "LANG_JS",
  "LANG_PYTHON",
  "MY_SQL",
  "POSTGRES_SQL",
  "DB_DESIGN",
  "ALGORITHMS",
  "DATA_STRUCTURES",
  "SYSTEM_ANALYSIS",
  "TEAMWORK",
  "COMMUNICATION",
  "RESPONSIBILITY",
  "INITIATIVE",
  "PROBLEM_SOLVING",
  "CREATIVITY",
  "LEADERSHIP",
];

module.exports = {
  ALLOWED_OPERATIONS,
  AVAILABLE_SUBJECTS,
};